#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BackupLite". #
#    @author Domenic Horner (gamerx)    #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

## How often show the backup run? (Default: "30M" / 30 Minutes)
# (Note: -1 or 0 will disable automatic backups.)
# Format: [Time][M-Minutes, H-Hours, D-Days, W-Weeks]
backupinterval: 30M

## How many backups are retained? (Default: 10)
# If this limit is hit, the oldest backup(s) will be removed. 
maxbackups: 10

backupemptyserver: false

## Directory to store backup in. (Default: backups)
# Note: Path can be relative, or absolute. ('D:/Backups', '/var/backups', 'altbackups', and '~/backups' are all valid)
backuppath: backups

## Worlds for the backup to skip. (Default: none)
# Seperate by a semicolon. eg. World1;World2;Nether
skipworlds:

## List of files to exclude/include from the plugin backup. (Default: none)
# Seperate by a semicolon. eg. Plugin1;Plugin2;Plugin3. This takes effect inside plugins/
pluginlist:

## Mode for the below list. (Default: true [Exclude listed files/folders])
# This can be true or false, false makes only the below plugin paths get included.
pluginlistmode: true