name: BackupLite
version: 0.5
description: A simple backup plugin.
authors: [gamerx]
website: http://www.bukkitbackup.com/
dev-url: http://dev.bukkit.org/server-mods/backup/
main: com.bukkitbackup.lite.BackupMain
commands:
  backup:
    description: Starts a backup of the server.
    usage: "Usage: /backup [args]"
  bu:
    description: Starts a backup of the server.
    usage: "Usage: /bu [args]"
permissions:
  backup.*:
    description: Gives access to all permissins.
    default: op
  backup.backup:
    description: Ability to perform backups
    default: false
  backup.reload:
    description: Reload backup's configuration
    default: false
  backup.notify:
    description: Players with this permissions get notified of backups.
    default: false
  backup.bypass:
    description: Players with this permission are not counted as online players.
    default: false
  backup.help:
    description: Able to view plugin's help menu.
    default: false
  backup.list:
    description: Able to list backups.
    default: false
  backup.config:
    description: Able to view configuration.
    default: false
  backup.log:
    description: Able to view log file.
    default: false
  backup.updateconf:
    description: Able to update the backups configuration file.
    default: false
  